apiVersion: v1
kind: Template
labels:
  template: manageiq-collector
metadata:
  name: manageiq-collector
  annotations:
    description: "ManageIQ Inventory Collector service"
    tags: "instant-app,manageiq,miq,collector-service"
    iconClass: "icon-rails"
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: manageiq-collector
    annotations:
      description: "Keeps track of the ManageIQ image changes"
  spec: {}
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    creationTimestamp: null
    name: manageiq-collector-${NAME}
  spec:
    replicas: 1
    selector:
      name: manageiq-collector-${NAME}
    strategy:
      type: Recreate
    template:
      metadata:
        creationTimestamp: null
        labels:
          name: manageiq-collector-${NAME}
      spec:
        containers:
        - capabilities: {}
          env:
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: "manageiq-secrets"
                key: pg-password
          - name: REDIS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: redis
                key: database-password
          - name: EMS
            value: "${NAME}"
          - name: BATCH_SIZE
            value: "${BATCH_SIZE}"
          image: ' '
          imagePullPolicy: IfNotPresent
          name: manageiq-collector
        restartPolicy: Always
    triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
        - manageiq-collector
        from:
          kind: ImageStreamTag
          name: manageiq-collector:latest
        lastTriggeredImage: ""
      type: ImageChange
    - type: ConfigChange
  status: {}
parameters:
  -
    name: "NAME"
    displayName: Name
    required: true
    description: "The name assigned to all of the frontend objects defined in this template."
    value: ems
  -
    name: BATCH_SIZE
    description: Batch Size for inv collection sent via kafka
    displayName: Batch Size for inv collection
    value: "1000"
  -
    name: EMS_ID
    description: Id of EMS
    displayName: Id of EMS
    from: '[0-9]{9}'
    generate: expression
    required: true
