kind: List
apiVersion: v1
metadata: {}

items:

- apiVersion: v1
  kind: Template
  metadata:
    name: redis-commander
  parameters:
  - name: NAME
    description: Name prefix for each object created
    required: true
    value: redis-commander
  - name: IMAGE
    description: Image with redis commander
    required: true
    value: tenstartups/redis-commander
  objects:
  - apiVersion: v1
    kind: DeploymentConfig
    metadata:
      name: ${NAME}
    spec:
      replicas: 1
      selector:
        deploymentconfig: ${NAME}
      template:
        metadata:
          labels:
            deploymentconfig: ${NAME}
        spec:
          containers:
          - name: redis-commander
            image: ${IMAGE}
            args:
            - --redis-host redis
            ports:
            - containerPort: 8081
  - apiVersion: v1
    kind: Service
    metadata:
      name: ${NAME}
    spec:
      ports:
      - name: ui
        port: 8081
      selector:
        deploymentconfig: ${NAME}
  - apiVersion: v1
    kind: Route
    metadata:
      name: ${NAME}
    spec:
      port:
        targetPort: http
      tls:
        termination: passthrough
      to:
        kind: Service
        name: ${NAME}

